global:
  scrape_interval: 15s

scrape_configs:
  - job_name: schoolhub-services
    metrics_path: /metrics
    static_configs:
      - targets:
          - auth-service:8000
          - school-service:8000
          - notification-service:8000
          - analytics-service:8000

  - job_name: telegram-worker
    static_configs:
      - targets:
          - telegram-worker:9000

  - job_name: api-gateway
    static_configs:
      - targets:
          - nginx-exporter:9113
